### PR TITLE
Updated Italian translations

### PR DESCRIPTION
**Pull request by mwithi**
Changed some translations from "capitalized each word" to "regular capitalization"

### CODE REVIEW

**Comment by gogolander** [comment]
A lot better: almost there. Still I have to reject it, sorry :(
Your pull contains invalid codes related to bug #267: the word "m5s" must disappear.
When you pull bugfixes cite all of them in the title of the pull request (in this case #272).

**Comment by mwithi** [comment]
I see... anyway the #272 is not linked the #267, because was an issue open on the capitalization of the labels, not on their specific content. The pull request point to solve the #272 only...

So, or we set the #272 as invalid and close and we concentrate on #267, or we can set as solved the first one, but in the late case the pull request should be accepted.

(just to be precise, doesn't matter if you accetp or reject it for me :) )

**Comment by gogolander** [comment]
Accepting it matters to me: work already done!
I would be glad to accept it.
You're right: the two bugs are not related one to another but they are present on the very same files.
That's why I rejected it. I can't pretend I didn't saw the bug.

**Comment by mwithi** [comment]
:+1:

**Pull request closed without merging**
