### PR TITLE
Updated translations

### PR DESCRIPTION
**Pull request by mwithi**
Changed some bundles from "each word capitalized" to "regular capitalization"

### CODE REVIEW

**Comment by gogolander** [comment]
your are in the wrong branch.

**Comment by mwithi** [comment]
please provide more informations... should I fork "test" branch and pull over there?

**Comment by gogolander** [comment]
as told you thursday, you have to sync to branch test and take care that it is always synced with the test brach in the upstream repo (this one).

**Comment by mwithi** [comment]
sorry, too many informations at the same time :p

**Comment by gogolander** [comment]
Don't worry.

**Pull request closed without merging**
